### ISSUE TITLE
[BUG] Fox5Image.toPIL() appears to produce incorrect colors

### ISSUE THREAD

**Issue by agnewhawk** [FelixWolf/libfurc#13]
**The bug**
When using Fox5Image.toPIL() to convert a Fox5 image to a PIL image, the resultant image appears to have incorrect colors

1. Original Test Image as in Fox Editor
![image](https://user-images.githubusercontent.com/81265289/183266273-b094a5ef-2156-4f23-b8ff-bd2b127aabfe.png)

2. Resulting image that was saved from the PIL object produced by Fox5Image.toPIL() - It appears that only the green channel from the image and arbitrary transparency is saved.
![testcard](https://user-images.githubusercontent.com/81265289/183266235-05742e19-da95-4d1e-a5db-e2c18bb0d999.png)

**Proposed solution**

It appears that the issue is on this line here.
https://github.com/FelixWolf/libfurc/blob/58410b1d9332db81b4a342a52a43a2ae36989a6a/libfurc/fox5.py#L67

When the line is substituted as follows
```python
data += bytes((self.data[pixel+1], self.data[pixel+2], self.data[pixel+3], self.data[pixel+0])) 
```

the colors should be saved correctly.

**Test code**
Below is the code snippet I used to save the above images from a fox file, for reference - in case there's something in my code that may have caused the issue instead.

```python
from libfurc import fox5

def getImage(fox,id):
    return fox.body["ImageList"][id]

fox = fox5.load("exportTest.fox")
img = getImage(fox,0)
img = img.toPIL()
img.save("testcard.png")
#img.show()
```

**Comment by FelixWolf** [comment]
Thanks you for the report!

Looks like I was trying to the ARGB pixel as if I were going to encode it(thus encoding it as BARG).
This has been fixed as of 6b14c1b.
